routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Login/Logout Routes
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::group(['middleware' => ['auth']], function () {
    /*
     * Main
     */
    Route::get('/', 'PagesController@dashboard');
    Route::get('dashboard', 'PagesController@dashboard')->name('dashboard');

    /*
     * Users
     */
    Route::group(['prefix' => 'users'], function () {
        Route::get('/data', 'UsersController@anyData')->name('users.data');
        Route::get('/taskdata/{id}', 'UsersController@taskData')->name('users.taskdata');
        Route::get('/leaddata/{id}', 'UsersController@leadData')->name('users.leaddata');
        Route::get('/clientdata/{id}', 'UsersController@clientData')->name('users.clientdata');
        Route::get('/users', 'UsersController@users')->name('users.users');
        
    });
    Route::resource('users', 'UsersController', ['middleware' => 'App\Http\Middleware\User\CanUserRead' ]);
    Route::get('/unactive_user/{id}','UsersController@unactive_user');
    Route::get('/active_user/{id}','UsersController@active_user');
    Route::get('/users/{id}/delete','UsersController@destroy');

    /*
    * Roles
    */
    Route::resource('roles', 'RolesController');

    /*
     * Clients
     */
    Route::group(['prefix' => 'clients'], function () {
        Route::get('/data', 'ClientsController@anyData')->name('clients.data');
        Route::get('/my', 'ClientsController@my')->name('clients.my');
        Route::get('/mydata', 'ClientsController@myData')->name('clients.mydata');
        Route::post('/create/cvrapi', 'ClientsController@cvrapiStart');
        Route::post('/upload/{id}', 'DocumentsController@upload');
        Route::patch('/updateassign/{id}', 'ClientsController@updateAssign');
        Route::get('masseClient', 'MasseClientsController@masseClient');

        Route::post('importExcel', 'MasseClientsController@importExcel');
        Route::get('masseUpdate', 'ClientsController@masseUpdate');
        Route::post('updateMasse', 'ClientsController@updateMasse');

        

    });
    Route::resource('clients', 'ClientsController', ['middleware' => 'App\Http\Middleware\Client\CanClientRead' ]);
    Route::resource('documents', 'DocumentsController');

    /*
     * Contacts
     */
    Route::group(['prefix' => 'contacts'], function () {
    Route::get('/data', 'ContactsController@anyData')->name('contacts.data');
    Route::get('/my', 'ContactsController@my')->name('contacts.my');
    Route::get('/mydata', 'ContactsController@myData')->name('contacts.mydata');
    Route::get('masseEquipement', 'MasseEquipementsController@masseEquipement');
    Route::get('teaser', 'ContactsController@teaser');

    Route::post('importExcelme', 'MasseEquipementsController@importExcelme');
    Route::post('exportExcelme', 'MasseEquipementsController@getExport');
    
    Route::get('masseUpdate', 'MasseEquipementsController@masseUpdate');
    Route::post('updateMasse', 'MasseEquipementsController@updateMasse');
    
    //V2
    Route::get('/ajouter', 'V2Controller@create')->name('equipement.abonn');
    Route::post('/ajouter', 'V2Controller@store')->name('equipement.abonnement');
    Route::post('/valider/{id}', 'V2Controller@valider')->name('valider');
    Route::post('/refuser/{id}', 'V2Controller@refuser')->name('refuser');
    Route::get('/equipement/{id}/edit', 'V2Controller@edit')->name('equipement.edit');
    Route::patch('/equipement/{id}', 'V2Controller@update')->name('equipement.update');
    Route::get('/filter', 'V2Controller@filter')->name('filter');
    Route::get('/filterfac', 'V2Controller@filterfac')->name('filterfac');
    Route::get('/facturation', 'V2Controller@facturation')->name('facturation');
    Route::post('/destroyabo/{id}', 'V2Controller@destroyabo')->name('destroy.abo');
    /* Route::get('/autocomplete', 'V2Controller@autocomplete')->name('autocomplete'); */





    });
    Route::resource('contacts', 'ContactsController', ['middleware' => 'App\Http\Middleware\Contact\CanContactRead' ]);

    /*
     * Tasks
     */
    Route::group(['prefix' => 'tasks'], function () {
        Route::get('/data', 'TasksController@anyData')->name('tasks.data');
        Route::get('/my', 'TasksController@my')->name('tasks.my');
        Route::get('/mydata', 'TasksController@myData')->name('tasks.mydata');
        Route::patch('/updatestatus/{id}', 'TasksController@updateStatus');
        Route::patch('/updateassign/{id}', 'TasksController@updateAssign');
        Route::post('/updatetime/{id}', 'TasksController@updateTime');
    });
    Route::resource('tasks', 'TasksController');

    /*
     * Leads
     */
    Route::group(['prefix' => 'leads'], function () {
        Route::get('/data', 'LeadsController@anyData')->name('leads.data');
        Route::get('/my', 'LeadsController@my')->name('leads.my');
        Route::get('/mydata', 'LeadsController@myData')->name('leads.mydata');
        Route::patch('/updateassign/{id}', 'LeadsController@updateAssign');
        Route::patch('/updatestatus/{id}', 'LeadsController@updateStatus');
        Route::patch('/updatefollowup/{id}', 'LeadsController@updateFollowup')->name('leads.followup');
    });
    Route::resource('leads', 'LeadsController');
    Route::post('/comments/{type}/{id}', 'CommentController@store');
    /*
     * Settings
     */
    Route::group(['prefix' => 'settings'], function () {
        Route::get('/', 'SettingsController@index')->name('settings.index');
        Route::patch('/permissionsUpdate', 'SettingsController@permissionsUpdate');
        Route::patch('/overall', 'SettingsController@updateOverall');
    });

    /*
     * Departments
     */
    Route::resource('departments', 'DepartmentsController');

    /*
     * Pays
     */
     Route::resource('pays', 'PaysController');
     Route::resource('chargeds', 'ChargedController');

    /*
     * Abonnements
     */
     Route::resource('abonnements', 'AbonnementsController', ['middleware' => 'App\Http\Middleware\Abonnement\CanAbonnementRead' ]);
     Route::get('/unactive_abonnement/{id}','AbonnementsController@unactive_abonnement');
     Route::get('/active_abonnement/{id}','AbonnementsController@active_abonnement');
     Route::get('/exporte','AbonnementsController@exporte');

    /*
     * Boitiers
     */
     Route::resource('boitiers', 'BoitiersController' , ['middleware' => 'App\Http\Middleware\Boitier\CanBoitierRead' ]);
     Route::get('/unactive_boitier/{id}','BoitiersController@unactive_boitier');
     Route::get('/active_boitier/{id}','BoitiersController@active_boitier');




    /*
     * Integrations
     */
    Route::group(['prefix' => 'integrations'], function () {
        Route::get('Integration/slack', 'IntegrationsController@slack');
    });
    Route::resource('integrations', 'IntegrationsController');

    /*
     * Notifications
     */
    Route::group(['prefix' => 'notifications'], function () {
        Route::post('/markread', 'NotificationsController@markRead')->name('notification.read');
        Route::get('/markall', 'NotificationsController@markAll');
        Route::get('/{id}', 'NotificationsController@markRead');
    });

    /*
     * Invoices
     */
    Route::group(['prefix' => 'invoices'], function () {
        Route::post('/updatepayment/{id}', 'InvoicesController@updatePayment')->name('invoice.payment.date');
        Route::post('/reopenpayment/{id}', 'InvoicesController@reopenPayment')->name('invoice.payment.reopen');
        Route::post('/sentinvoice/{id}', 'InvoicesController@updateSentStatus')->name('invoice.sent');
        Route::post('/newitem/{id}', 'InvoicesController@newItem')->name('invoice.new.item');
    });
    Route::resource('invoices', 'InvoicesController');
});
Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

    /*
    * Excel
    */
    // Route::get('importExport', 'MaatwebsiteDemoController@importExport');
    // Route::get('downloadExcel/{type}', 'MaatwebsiteDemoController@downloadExcel');
    // Route::post('importExcel', 'MaatwebsiteDemoController@importExcel');

    /*
    * Masse CLIENT
    */
    
   

    /*
    * Masse Equipement
    */
    
    

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $fillable = [
        'task_complete_allowed',
        'task_assign_allowed',
        'lead_complete_allowed',
        'lead_assign_allowed',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function tasks()
    {
        return $this->belongsTo(Task::class);
    }
}

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use Session;
use Illuminate\Http\Request;
use App\Repositories\Setting\SettingRepositoryContract;
use App\Repositories\Role\RoleRepositoryContract;
use App\Http\Requests\Setting\UpdateSettingOverallRequest;

class SettingsController extends Controller
{
    protected $settings;
    protected $roles;

    /**
     * SettingsController constructor.
     *
     * @param SettingRepositoryContract $settings
     * @param RoleRepositoryContract    $roles
     */
    public function __construct(
        SettingRepositoryContract $settings,
        RoleRepositoryContract $roles
    ) {
        $this->settings = $settings;
        $this->roles    = $roles;
        $this->middleware('user.is.admin', ['only' => ['index']]);
    }

    /**
     * @return mixed
     */
    public function index()
    {
        return view('settings.index')
            ->withSettings($this->settings->getSetting())
            ->withPermission($this->roles->allPermissions())
            ->withRoles($this->roles->allRoles());
    }

    /**
     * @param UpdateSettingOverallRequest $request
     *
     * @return mixed
     */
    public function updateOverall(UpdateSettingOverallRequest $request)
    {
        $this->settings->updateOverall($request);
        Session::flash('flash_message', 'Overall settings successfully updated');

        return redirect()->back();
    }

    /**
     * @param Request $request
     *
     * @return mixed
     */
    public function permissionsUpdate(Request $request)
    {
        $this->roles->permissionsUpdate($request);
        Session::flash('flash_message', 'Role is updated');

        return redirect()->back();
    }
}

resources/views/settings/index.blade.php
@extends('layouts.master')
@section('heading')
    <h1>{{ __('header.Settings') }}</h1>
@stop
@section('content')
<div id="div1" style="height: 100%;position:relative;">
    <div id="div2" style="max-height:100%;overflow:auto;">
        <div id="div3" style="height:100%;">
   
    @foreach($roles as $role) 
    <div class="col-lg-12" >
    {!! Form::model($permission, [
        'method' => 'PATCH',
        'url'    => 'settings/permissionsUpdate',
    ]) !!}

        <table class="table table-responsive table-striped  table-bordered" id="permissions-table" >
            <thead>
            <tr>
            <th></th>
                @foreach($permission as $perm)
             <th>{{$perm->display_name}}</th>
             

                @endforeach
                
                <th></th>
            </tr>

            </thead>
            
            <tbody>
        <input type="hidden" name="role_id" value="{{ $role->id }}"/>
                <tr>
                        <th>{{$role->display_name}}</th>
                        
                        @foreach($permission as $perm)
                        
                            <?php $isEnabled = !current( array_filter($role->permissions->toArray(),
                                        function ($element) use ($perm) {
                                            return $element['id'] === $perm->id;
                                        }
                                    )
                            );  ?>

                            <td><input type="checkbox"
                                       <?php if (!$isEnabled) {
                                echo 'checked';
                            } ?> name="permissions[ {{ $perm->id }} ]"
                                       value="1" data-role="{{ $role->id }}">
                                <span class="perm-name"></span><br/></td>

                
                    @endforeach        
    <td>{!! Form::submit( __('Save Role') , ['class' => 'btn btn-sm btn-warning']) !!}
    </td>
  
   
            </tr>
      </tbody>
    </table>
     {!! Form::close() !!}
     </div>
     @endforeach
</div>


</div>
</div>

    {{-- <div class="row">
        <div class="col-lg-12">
            <div class="sidebarheader movedown"><p>{{ __('Overall Settings') }}</p></div>


            {!! Form::model($settings, [
               'method' => 'PATCH',
               'url' => 'settings/overall'
               ]) !!} --}}
{{-- 
                    <!-- *********************************************************************
     *                     Task complete       
     *********************************************************************-->
            <div class="panel panel-default movedown">
                <div class="panel-heading">{{ __('Task completion') }}</div>
                <div class="panel-body">

                    {{ __('If Allowed only user who are assigned the task & the admin can complete the task.') }} <br/>
                    {{ __('If Not allowed anyone, can complete all tasks.')}}
                </div>
            </div>
            {!! Form::select('task_complete_allowed', 
            [
                1 => __('Allowed'), 
                2 => __('Not allowed')
            ], 
            $settings->task_complete_allowed, ['class' => 'form-control']) !!}
                    <!-- *********************************************************************
     *                     Task assign       
     *********************************************************************-->
            <div class="panel panel-default movedown">
                <div class="panel-heading">{{ __('Task assigning') }}</div>
                <div class="panel-body">

                   {{ __('If Allowed only user who are assigned the task &amp; the admin can assign another user.') }} <br/>
                    {{ __('If Not allowed anyone, can assign another user.') }}
                </div>
            </div>
            {!! Form::select('task_assign_allowed', 
            [
                1 => __('Allowed'), 
                2 => __('Not allowed')
            ],
            $settings->task_assign_allowed, ['class' => 'form-control']) !!}
                    <!-- *********************************************************************
     *                     Lead complete       
     *********************************************************************-->

            <div class="panel panel-default movedown">
                <div class="panel-heading">{{ __('Lead completion') }}</div>
                <div class="panel-body">

                    {{ __('If Allowed only user who are assigned the lead & the admin can complete the lead.') }} <br/>
                    {{ __('If Not allowed anyone, can complete all leads.')}}
                </div>
            </div>
            {!! Form::select('lead_complete_allowed', [
                1 => __('Allowed'), 
                2 => __('Not allowed')
            ], 
            $settings->lead_complete_allowed, ['class' => 'form-control']) !!}
                    <!-- *********************************************************************
     *                     Lead assign       
     *********************************************************************-->
            <div class="panel panel-default movedown">
                <div class="panel-heading">{{ __('Lead assigning') }}</div>
                <div class="panel-body">

                    {{ __('If Allowed only user who are assigned the lead & the admin can complete the lead.') }} <br/>
                    {{ __('If Not allowed anyone, can complete all leads.')}}
                </div>
            </div>
            {!! Form::select('lead_assign_allowed', 
            [
                1 => __('Allowed'), 
                2 => __('Not allowed')
            ], 
            $settings->lead_assign_allowed, ['class' => 'form-control']) !!}
            <br/> --}}
            {{-- {!! Form::submit( __('Save overall settings'), ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!} --}}
             <a href="{{ route('roles.index')}}"
                       class="btn btn-sm btn-warning">{{ __('Save') }}</a>

{{--    
        </div>
    </div> --}}

@stop